# Generated by Django 4.1.7 on 2024-01-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binance_all_pairs_trading_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=15)),
                ('immutableNameBaseAsset', models.CharField(blank=True, max_length=15)),
                ('immutableNameQuoteAsset', models.CharField(blank=True, max_length=15)),
                ('baseAsset', models.CharField(blank=True, max_length=15)),
                ('quoteAsset', models.CharField(blank=True, max_length=15)),
                ('stepSize', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Binance_BookTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=15)),
                ('bidPrice', models.CharField(blank=True, max_length=25)),
                ('bidQty', models.CharField(blank=True, max_length=25)),
                ('askPrice', models.CharField(blank=True, max_length=25)),
                ('askQty', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Binance_pairs_strategy_b_s_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_a', models.CharField(blank=True, max_length=15)),
                ('baseCurrency_a', models.CharField(blank=True, max_length=15)),
                ('quoteAsset_a', models.CharField(blank=True, max_length=15)),
                ('stepSize_a', models.FloatField(blank=True, default=0)),
                ('symbol_b', models.CharField(blank=True, max_length=15)),
                ('baseCurrency_b', models.CharField(blank=True, max_length=15)),
                ('quoteAsset_b', models.CharField(blank=True, max_length=15)),
                ('stepSize_b', models.FloatField(blank=True, default=0)),
                ('symbol_c', models.CharField(blank=True, max_length=15)),
                ('baseCurrency_c', models.CharField(blank=True, max_length=15)),
                ('quoteAsset_c', models.CharField(blank=True, max_length=15)),
                ('stepSize_c', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Binance_profit_tradeMaker_bss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols', models.TextField(blank=True)),
                ('symbol_a', models.CharField(blank=True, max_length=15)),
                ('baseCurrency_a', models.CharField(blank=True, max_length=15)),
                ('quoteAsset_a', models.CharField(blank=True, max_length=15)),
                ('stepSize_a', models.CharField(blank=True, max_length=25)),
                ('bidPrice_a', models.CharField(blank=True, max_length=25)),
                ('bidQty_a', models.CharField(blank=True, max_length=25)),
                ('askPrice_a', models.CharField(blank=True, max_length=25)),
                ('askQty_a', models.CharField(blank=True, max_length=25)),
                ('symbol_b', models.CharField(blank=True, max_length=15)),
                ('baseCurrency_b', models.CharField(blank=True, max_length=15)),
                ('quoteAsset_b', models.CharField(blank=True, max_length=15)),
                ('stepSize_b', models.CharField(blank=True, max_length=25)),
                ('bidPrice_b', models.CharField(blank=True, max_length=25)),
                ('bidQty_b', models.CharField(blank=True, max_length=25)),
                ('askPrice_b', models.CharField(blank=True, max_length=25)),
                ('askQty_b', models.CharField(blank=True, max_length=25)),
                ('symbol_c', models.CharField(blank=True, max_length=15)),
                ('baseCurrency_c', models.CharField(blank=True, max_length=15)),
                ('quoteAsset_c', models.CharField(blank=True, max_length=15)),
                ('stepSize_c', models.CharField(blank=True, max_length=25)),
                ('bidPrice_c', models.CharField(blank=True, max_length=25)),
                ('bidQty_c', models.CharField(blank=True, max_length=25)),
                ('askPrice_c', models.CharField(blank=True, max_length=25)),
                ('askQty_c', models.CharField(blank=True, max_length=25)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bybit_all_pairs_trading_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=15)),
                ('immutableNameBaseAsset', models.CharField(blank=True, max_length=15)),
                ('immutableNameQuoteAsset', models.CharField(blank=True, max_length=15)),
                ('baseAsset', models.CharField(blank=True, max_length=15)),
                ('quoteAsset', models.CharField(blank=True, max_length=15)),
                ('stepSize', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradedBundlesCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairSymbols_A', models.CharField(blank=True, max_length=15)),
                ('pairSymbols_B', models.CharField(blank=True, max_length=15)),
                ('pairSymbols_C', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
